=== ankititmuniversity/swagger/src/test/resources/schema/user_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "User",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "username": {
      "type": "string"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "password": {
      "type": "string"
    },
    "phone": {
      "type": "string",
      "pattern": "^[0-9]{10}$"
    },
    "userStatus": {
      "type": "integer"
    }
  },
  "required": [
    "id",
    "username",
    "firstName",
    "lastName",
    "email",
    "password",
    "phone",
    "userStatus"
  ],
  "additionalProperties": false
}

=== ankititmuniversity/swagger/src/test/resources/jsonData/user_payload.json
[
 {
  "id": 1,
  "username": "mohan",
  "firstName": "Mohan",
  "lastName": "Kumar",
  "email": "mohan@kumar.com",
  "password": "Test@123",
  "phone": "0412345678",
  "userStatus": 1
},
{
  "id": 2,
  "username": "ankitkumar",
  "firstName": "Ankit",
  "lastName": "Kumar",
  "email": "ankit@kumar.com",
  "password": "Test@123",
  "phone": "0412345678",
  "userStatus": 0
},{
  "id": 3,
  "username": "rahul",
  "firstName": "Rahul",
  "lastName": "Kumar",
  "email": "rahul@kumar.com",
  "password": "Test@123",
  "phone": "0412345678",
  "userStatus": 1
}
]
